// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ps {
class Meta;
class MetaDefaultTypeInternal;
extern MetaDefaultTypeInternal _Meta_default_instance_;
class Meta_Node_;
class Meta_Node_DefaultTypeInternal;
extern Meta_Node_DefaultTypeInternal _Meta_Node__default_instance_;
}  // namespace ps

namespace ps {

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_message_2eproto

// ===================================================================

class Meta_Node_ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ps.Meta.Node_) */ {
 public:
  Meta_Node_();
  virtual ~Meta_Node_();

  Meta_Node_(const Meta_Node_& from);

  inline Meta_Node_& operator=(const Meta_Node_& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Meta_Node_& default_instance();

  static inline const Meta_Node_* internal_default_instance() {
    return reinterpret_cast<const Meta_Node_*>(
               &_Meta_Node__default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Meta_Node_* other);

  // implements Message ----------------------------------------------

  inline Meta_Node_* New() const PROTOBUF_FINAL { return New(NULL); }

  Meta_Node_* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Meta_Node_& from);
  void MergeFrom(const Meta_Node_& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Meta_Node_* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string hostname = 3;
  bool has_hostname() const;
  void clear_hostname();
  static const int kHostnameFieldNumber = 3;
  const ::std::string& hostname() const;
  void set_hostname(const ::std::string& value);
  #if LANG_CXX11
  void set_hostname(::std::string&& value);
  #endif
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  ::std::string* mutable_hostname();
  ::std::string* release_hostname();
  void set_allocated_hostname(::std::string* hostname);

  // required int32 role = 1;
  bool has_role() const;
  void clear_role();
  static const int kRoleFieldNumber = 1;
  ::google::protobuf::int32 role() const;
  void set_role(::google::protobuf::int32 value);

  // required int32 id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 port = 4;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 4;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // optional bool is_recovery = 5;
  bool has_is_recovery() const;
  void clear_is_recovery();
  static const int kIsRecoveryFieldNumber = 5;
  bool is_recovery() const;
  void set_is_recovery(bool value);

  // @@protoc_insertion_point(class_scope:ps.Meta.Node_)
 private:
  void set_has_role();
  void clear_has_role();
  void set_has_id();
  void clear_has_id();
  void set_has_hostname();
  void clear_has_hostname();
  void set_has_port();
  void clear_has_port();
  void set_has_is_recovery();
  void clear_has_is_recovery();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr hostname_;
  ::google::protobuf::int32 role_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 port_;
  bool is_recovery_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Meta : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ps.Meta) */ {
 public:
  Meta();
  virtual ~Meta();

  Meta(const Meta& from);

  inline Meta& operator=(const Meta& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Meta& default_instance();

  static inline const Meta* internal_default_instance() {
    return reinterpret_cast<const Meta*>(
               &_Meta_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Meta* other);

  // implements Message ----------------------------------------------

  inline Meta* New() const PROTOBUF_FINAL { return New(NULL); }

  Meta* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Meta& from);
  void MergeFrom(const Meta& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Meta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Meta_Node_ Node_;

  // accessors -------------------------------------------------------

  // repeated .ps.Meta.Node_ node = 7;
  int node_size() const;
  void clear_node();
  static const int kNodeFieldNumber = 7;
  const ::ps::Meta_Node_& node(int index) const;
  ::ps::Meta_Node_* mutable_node(int index);
  ::ps::Meta_Node_* add_node();
  ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >*
      mutable_node();
  const ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >&
      node() const;

  // repeated int32 data_type = 8;
  int data_type_size() const;
  void clear_data_type();
  static const int kDataTypeFieldNumber = 8;
  ::google::protobuf::int32 data_type(int index) const;
  void set_data_type(int index, ::google::protobuf::int32 value);
  void add_data_type(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data_type() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data_type();

  // required int32 cmd = 1;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::int32 cmd() const;
  void set_cmd(::google::protobuf::int32 value);

  // required int32 sender = 2;
  bool has_sender() const;
  void clear_sender();
  static const int kSenderFieldNumber = 2;
  ::google::protobuf::int32 sender() const;
  void set_sender(::google::protobuf::int32 value);

  // required int32 receiver = 3;
  bool has_receiver() const;
  void clear_receiver();
  static const int kReceiverFieldNumber = 3;
  ::google::protobuf::int32 receiver() const;
  void set_receiver(::google::protobuf::int32 value);

  // required int32 timestamp = 4;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 4;
  ::google::protobuf::int32 timestamp() const;
  void set_timestamp(::google::protobuf::int32 value);

  // required bool request = 5;
  bool has_request() const;
  void clear_request();
  static const int kRequestFieldNumber = 5;
  bool request() const;
  void set_request(bool value);

  // required bool push = 6;
  bool has_push() const;
  void clear_push();
  static const int kPushFieldNumber = 6;
  bool push() const;
  void set_push(bool value);

  // optional int32 customer_id = 9;
  bool has_customer_id() const;
  void clear_customer_id();
  static const int kCustomerIdFieldNumber = 9;
  ::google::protobuf::int32 customer_id() const;
  void set_customer_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ps.Meta)
 private:
  void set_has_cmd();
  void clear_has_cmd();
  void set_has_sender();
  void clear_has_sender();
  void set_has_receiver();
  void clear_has_receiver();
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_request();
  void clear_has_request();
  void set_has_push();
  void clear_has_push();
  void set_has_customer_id();
  void clear_has_customer_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ > node_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_type_;
  ::google::protobuf::int32 cmd_;
  ::google::protobuf::int32 sender_;
  ::google::protobuf::int32 receiver_;
  ::google::protobuf::int32 timestamp_;
  bool request_;
  bool push_;
  ::google::protobuf::int32 customer_id_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Meta_Node_

// required int32 role = 1;
inline bool Meta_Node_::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Meta_Node_::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Meta_Node_::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Meta_Node_::clear_role() {
  role_ = 0;
  clear_has_role();
}
inline ::google::protobuf::int32 Meta_Node_::role() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.role)
  return role_;
}
inline void Meta_Node_::set_role(::google::protobuf::int32 value) {
  set_has_role();
  role_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.role)
}

// required int32 id = 2;
inline bool Meta_Node_::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Meta_Node_::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Meta_Node_::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Meta_Node_::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Meta_Node_::id() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.id)
  return id_;
}
inline void Meta_Node_::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.id)
}

// required string hostname = 3;
inline bool Meta_Node_::has_hostname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Meta_Node_::set_has_hostname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Meta_Node_::clear_has_hostname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Meta_Node_::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hostname();
}
inline const ::std::string& Meta_Node_::hostname() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.hostname)
  return hostname_.GetNoArena();
}
inline void Meta_Node_::set_hostname(const ::std::string& value) {
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.hostname)
}
#if LANG_CXX11
inline void Meta_Node_::set_hostname(::std::string&& value) {
  set_has_hostname();
  hostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ps.Meta.Node_.hostname)
}
#endif
inline void Meta_Node_::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ps.Meta.Node_.hostname)
}
inline void Meta_Node_::set_hostname(const char* value, size_t size) {
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ps.Meta.Node_.hostname)
}
inline ::std::string* Meta_Node_::mutable_hostname() {
  set_has_hostname();
  // @@protoc_insertion_point(field_mutable:ps.Meta.Node_.hostname)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Meta_Node_::release_hostname() {
  // @@protoc_insertion_point(field_release:ps.Meta.Node_.hostname)
  clear_has_hostname();
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Meta_Node_::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    set_has_hostname();
  } else {
    clear_has_hostname();
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:ps.Meta.Node_.hostname)
}

// required int32 port = 4;
inline bool Meta_Node_::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Meta_Node_::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Meta_Node_::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Meta_Node_::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 Meta_Node_::port() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.port)
  return port_;
}
inline void Meta_Node_::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.port)
}

// optional bool is_recovery = 5;
inline bool Meta_Node_::has_is_recovery() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Meta_Node_::set_has_is_recovery() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Meta_Node_::clear_has_is_recovery() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Meta_Node_::clear_is_recovery() {
  is_recovery_ = false;
  clear_has_is_recovery();
}
inline bool Meta_Node_::is_recovery() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.is_recovery)
  return is_recovery_;
}
inline void Meta_Node_::set_is_recovery(bool value) {
  set_has_is_recovery();
  is_recovery_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.is_recovery)
}

// -------------------------------------------------------------------

// Meta

// required int32 cmd = 1;
inline bool Meta::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Meta::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Meta::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Meta::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 Meta::cmd() const {
  // @@protoc_insertion_point(field_get:ps.Meta.cmd)
  return cmd_;
}
inline void Meta::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.cmd)
}

// required int32 sender = 2;
inline bool Meta::has_sender() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Meta::set_has_sender() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Meta::clear_has_sender() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Meta::clear_sender() {
  sender_ = 0;
  clear_has_sender();
}
inline ::google::protobuf::int32 Meta::sender() const {
  // @@protoc_insertion_point(field_get:ps.Meta.sender)
  return sender_;
}
inline void Meta::set_sender(::google::protobuf::int32 value) {
  set_has_sender();
  sender_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.sender)
}

// required int32 receiver = 3;
inline bool Meta::has_receiver() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Meta::set_has_receiver() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Meta::clear_has_receiver() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Meta::clear_receiver() {
  receiver_ = 0;
  clear_has_receiver();
}
inline ::google::protobuf::int32 Meta::receiver() const {
  // @@protoc_insertion_point(field_get:ps.Meta.receiver)
  return receiver_;
}
inline void Meta::set_receiver(::google::protobuf::int32 value) {
  set_has_receiver();
  receiver_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.receiver)
}

// required int32 timestamp = 4;
inline bool Meta::has_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Meta::set_has_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Meta::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Meta::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 Meta::timestamp() const {
  // @@protoc_insertion_point(field_get:ps.Meta.timestamp)
  return timestamp_;
}
inline void Meta::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.timestamp)
}

// required bool request = 5;
inline bool Meta::has_request() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Meta::set_has_request() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Meta::clear_has_request() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Meta::clear_request() {
  request_ = false;
  clear_has_request();
}
inline bool Meta::request() const {
  // @@protoc_insertion_point(field_get:ps.Meta.request)
  return request_;
}
inline void Meta::set_request(bool value) {
  set_has_request();
  request_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.request)
}

// required bool push = 6;
inline bool Meta::has_push() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Meta::set_has_push() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Meta::clear_has_push() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Meta::clear_push() {
  push_ = false;
  clear_has_push();
}
inline bool Meta::push() const {
  // @@protoc_insertion_point(field_get:ps.Meta.push)
  return push_;
}
inline void Meta::set_push(bool value) {
  set_has_push();
  push_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.push)
}

// repeated .ps.Meta.Node_ node = 7;
inline int Meta::node_size() const {
  return node_.size();
}
inline void Meta::clear_node() {
  node_.Clear();
}
inline const ::ps::Meta_Node_& Meta::node(int index) const {
  // @@protoc_insertion_point(field_get:ps.Meta.node)
  return node_.Get(index);
}
inline ::ps::Meta_Node_* Meta::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:ps.Meta.node)
  return node_.Mutable(index);
}
inline ::ps::Meta_Node_* Meta::add_node() {
  // @@protoc_insertion_point(field_add:ps.Meta.node)
  return node_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >*
Meta::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:ps.Meta.node)
  return &node_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >&
Meta::node() const {
  // @@protoc_insertion_point(field_list:ps.Meta.node)
  return node_;
}

// repeated int32 data_type = 8;
inline int Meta::data_type_size() const {
  return data_type_.size();
}
inline void Meta::clear_data_type() {
  data_type_.Clear();
}
inline ::google::protobuf::int32 Meta::data_type(int index) const {
  // @@protoc_insertion_point(field_get:ps.Meta.data_type)
  return data_type_.Get(index);
}
inline void Meta::set_data_type(int index, ::google::protobuf::int32 value) {
  data_type_.Set(index, value);
  // @@protoc_insertion_point(field_set:ps.Meta.data_type)
}
inline void Meta::add_data_type(::google::protobuf::int32 value) {
  data_type_.Add(value);
  // @@protoc_insertion_point(field_add:ps.Meta.data_type)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Meta::data_type() const {
  // @@protoc_insertion_point(field_list:ps.Meta.data_type)
  return data_type_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Meta::mutable_data_type() {
  // @@protoc_insertion_point(field_mutable_list:ps.Meta.data_type)
  return &data_type_;
}

// optional int32 customer_id = 9;
inline bool Meta::has_customer_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Meta::set_has_customer_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Meta::clear_has_customer_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Meta::clear_customer_id() {
  customer_id_ = 0;
  clear_has_customer_id();
}
inline ::google::protobuf::int32 Meta::customer_id() const {
  // @@protoc_insertion_point(field_get:ps.Meta.customer_id)
  return customer_id_;
}
inline void Meta::set_customer_id(::google::protobuf::int32 value) {
  set_has_customer_id();
  customer_id_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.customer_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace ps

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
