// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ps {
class Meta_Node_DefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Meta_Node_> {
} _Meta_Node__default_instance_;
class MetaDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Meta> {
} _Meta_default_instance_;

namespace protobuf_message_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, role_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, hostname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta_Node_, is_recovery_),
  1,
  2,
  0,
  3,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, cmd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, receiver_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, request_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, push_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, node_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Meta, data_type_),
  0,
  1,
  2,
  3,
  4,
  5,
  ~0u,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 10, sizeof(Meta_Node_)},
  { 15, 28, sizeof(Meta)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Meta_Node__default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Meta_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Meta_Node__default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Meta_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Meta_Node__default_instance_.DefaultConstruct();
  _Meta_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rmessage.proto\022\002ps\"\372\003\n\004Meta\022\013\n\003cmd\030\001 \002("
      "\005\022\016\n\006sender\030\002 \002(\005\022\020\n\010receiver\030\003 \002(\005\022\021\n\tt"
      "imestamp\030\004 \002(\005\022\017\n\007request\030\005 \002(\010\022\014\n\004push\030"
      "\006 \002(\010\022\034\n\004node\030\007 \003(\0132\016.ps.Meta.Node_\022\021\n\td"
      "ata_type\030\010 \003(\005\032\206\001\n\005Node_\022\014\n\004role\030\001 \002(\005\022\n"
      "\n\002id\030\002 \002(\005\022\020\n\010hostname\030\003 \002(\t\022\014\n\004port\030\004 \002"
      "(\005\022\023\n\013is_recovery\030\005 \001(\010\".\n\005Role_\022\r\n\tSCHE"
      "DULER\020\000\022\n\n\006SERVER\020\001\022\n\n\006WORKER\020\002\"J\n\010Comma"
      "nd_\022\t\n\005EMPTY\020\000\022\014\n\010ADD_NODE\020\001\022\r\n\tTERMINAT"
      "E\020\002\022\007\n\003ACK\020\003\022\r\n\tHEARTBEAT\020\004\"\212\001\n\002t_\022\010\n\004CH"
      "AR\020\000\022\010\n\004INT8\020\001\022\t\n\005INT16\020\002\022\t\n\005INT32\020\003\022\t\n\005"
      "INT64\020\004\022\t\n\005UINT8\020\005\022\n\n\006UINT16\020\006\022\n\n\006UINT32"
      "\020\007\022\n\n\006UINT64\020\010\022\t\n\005FLOAT\020\t\022\n\n\006DOUBLE\020\n\022\t\n"
      "\005OTHER\020\013"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 528);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_message_2eproto

const ::google::protobuf::EnumDescriptor* Meta_Node__Role__descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[0];
}
bool Meta_Node__Role__IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Meta_Node__Role_ Meta_Node_::SCHEDULER;
const Meta_Node__Role_ Meta_Node_::SERVER;
const Meta_Node__Role_ Meta_Node_::WORKER;
const Meta_Node__Role_ Meta_Node_::Role__MIN;
const Meta_Node__Role_ Meta_Node_::Role__MAX;
const int Meta_Node_::Role__ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Meta_Command__descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[1];
}
bool Meta_Command__IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Meta_Command_ Meta::EMPTY;
const Meta_Command_ Meta::ADD_NODE;
const Meta_Command_ Meta::TERMINATE;
const Meta_Command_ Meta::ACK;
const Meta_Command_ Meta::HEARTBEAT;
const Meta_Command_ Meta::Command__MIN;
const Meta_Command_ Meta::Command__MAX;
const int Meta::Command__ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Meta_t__descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[2];
}
bool Meta_t__IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Meta_t_ Meta::CHAR;
const Meta_t_ Meta::INT8;
const Meta_t_ Meta::INT16;
const Meta_t_ Meta::INT32;
const Meta_t_ Meta::INT64;
const Meta_t_ Meta::UINT8;
const Meta_t_ Meta::UINT16;
const Meta_t_ Meta::UINT32;
const Meta_t_ Meta::UINT64;
const Meta_t_ Meta::FLOAT;
const Meta_t_ Meta::DOUBLE;
const Meta_t_ Meta::OTHER;
const Meta_t_ Meta::t__MIN;
const Meta_t_ Meta::t__MAX;
const int Meta::t__ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Meta_Node_::kRoleFieldNumber;
const int Meta_Node_::kIdFieldNumber;
const int Meta_Node_::kHostnameFieldNumber;
const int Meta_Node_::kPortFieldNumber;
const int Meta_Node_::kIsRecoveryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Meta_Node_::Meta_Node_()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ps.Meta.Node_)
}
Meta_Node_::Meta_Node_(const Meta_Node_& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_hostname()) {
    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  ::memcpy(&role_, &from.role_,
    reinterpret_cast<char*>(&is_recovery_) -
    reinterpret_cast<char*>(&role_) + sizeof(is_recovery_));
  // @@protoc_insertion_point(copy_constructor:ps.Meta.Node_)
}

void Meta_Node_::SharedCtor() {
  _cached_size_ = 0;
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&role_, 0, reinterpret_cast<char*>(&is_recovery_) -
    reinterpret_cast<char*>(&role_) + sizeof(is_recovery_));
}

Meta_Node_::~Meta_Node_() {
  // @@protoc_insertion_point(destructor:ps.Meta.Node_)
  SharedDtor();
}

void Meta_Node_::SharedDtor() {
  hostname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Meta_Node_::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Meta_Node_::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Meta_Node_& Meta_Node_::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Meta_Node_* Meta_Node_::New(::google::protobuf::Arena* arena) const {
  Meta_Node_* n = new Meta_Node_;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Meta_Node_::Clear() {
// @@protoc_insertion_point(message_clear_start:ps.Meta.Node_)
  if (has_hostname()) {
    GOOGLE_DCHECK(!hostname_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*hostname_.UnsafeRawStringPointer())->clear();
  }
  if (_has_bits_[0 / 32] & 30u) {
    ::memset(&role_, 0, reinterpret_cast<char*>(&is_recovery_) -
      reinterpret_cast<char*>(&role_) + sizeof(is_recovery_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Meta_Node_::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ps.Meta.Node_)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 role = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_role();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &role_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string hostname = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->hostname().data(), this->hostname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ps.Meta.Node_.hostname");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 port = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          set_has_port();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool is_recovery = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {
          set_has_is_recovery();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_recovery_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ps.Meta.Node_)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ps.Meta.Node_)
  return false;
#undef DO_
}

void Meta_Node_::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ps.Meta.Node_)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 role = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->role(), output);
  }

  // required int32 id = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // required string hostname = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostname().data(), this->hostname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ps.Meta.Node_.hostname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->hostname(), output);
  }

  // required int32 port = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->port(), output);
  }

  // optional bool is_recovery = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->is_recovery(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ps.Meta.Node_)
}

::google::protobuf::uint8* Meta_Node_::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ps.Meta.Node_)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 role = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->role(), target);
  }

  // required int32 id = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // required string hostname = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostname().data(), this->hostname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ps.Meta.Node_.hostname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->hostname(), target);
  }

  // required int32 port = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->port(), target);
  }

  // optional bool is_recovery = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->is_recovery(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ps.Meta.Node_)
  return target;
}

size_t Meta_Node_::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:ps.Meta.Node_)
  size_t total_size = 0;

  if (has_hostname()) {
    // required string hostname = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostname());
  }

  if (has_role()) {
    // required int32 role = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->role());
  }

  if (has_id()) {
    // required int32 id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  if (has_port()) {
    // required int32 port = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->port());
  }

  return total_size;
}
size_t Meta_Node_::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ps.Meta.Node_)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required string hostname = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostname());

    // required int32 role = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->role());

    // required int32 id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());

    // required int32 port = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->port());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional bool is_recovery = 5;
  if (has_is_recovery()) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Meta_Node_::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ps.Meta.Node_)
  GOOGLE_DCHECK_NE(&from, this);
  const Meta_Node_* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Meta_Node_>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ps.Meta.Node_)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ps.Meta.Node_)
    MergeFrom(*source);
  }
}

void Meta_Node_::MergeFrom(const Meta_Node_& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ps.Meta.Node_)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_hostname();
      hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
    }
    if (cached_has_bits & 0x00000002u) {
      role_ = from.role_;
    }
    if (cached_has_bits & 0x00000004u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000008u) {
      port_ = from.port_;
    }
    if (cached_has_bits & 0x00000010u) {
      is_recovery_ = from.is_recovery_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Meta_Node_::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ps.Meta.Node_)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Meta_Node_::CopyFrom(const Meta_Node_& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ps.Meta.Node_)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Meta_Node_::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  return true;
}

void Meta_Node_::Swap(Meta_Node_* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Meta_Node_::InternalSwap(Meta_Node_* other) {
  hostname_.Swap(&other->hostname_);
  std::swap(role_, other->role_);
  std::swap(id_, other->id_);
  std::swap(port_, other->port_);
  std::swap(is_recovery_, other->is_recovery_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Meta_Node_::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Meta_Node_

// required int32 role = 1;
bool Meta_Node_::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Meta_Node_::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
void Meta_Node_::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
void Meta_Node_::clear_role() {
  role_ = 0;
  clear_has_role();
}
::google::protobuf::int32 Meta_Node_::role() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.role)
  return role_;
}
void Meta_Node_::set_role(::google::protobuf::int32 value) {
  set_has_role();
  role_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.role)
}

// required int32 id = 2;
bool Meta_Node_::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Meta_Node_::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
void Meta_Node_::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
void Meta_Node_::clear_id() {
  id_ = 0;
  clear_has_id();
}
::google::protobuf::int32 Meta_Node_::id() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.id)
  return id_;
}
void Meta_Node_::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.id)
}

// required string hostname = 3;
bool Meta_Node_::has_hostname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Meta_Node_::set_has_hostname() {
  _has_bits_[0] |= 0x00000001u;
}
void Meta_Node_::clear_has_hostname() {
  _has_bits_[0] &= ~0x00000001u;
}
void Meta_Node_::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hostname();
}
const ::std::string& Meta_Node_::hostname() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.hostname)
  return hostname_.GetNoArena();
}
void Meta_Node_::set_hostname(const ::std::string& value) {
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.hostname)
}
#if LANG_CXX11
void Meta_Node_::set_hostname(::std::string&& value) {
  set_has_hostname();
  hostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ps.Meta.Node_.hostname)
}
#endif
void Meta_Node_::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ps.Meta.Node_.hostname)
}
void Meta_Node_::set_hostname(const char* value, size_t size) {
  set_has_hostname();
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ps.Meta.Node_.hostname)
}
::std::string* Meta_Node_::mutable_hostname() {
  set_has_hostname();
  // @@protoc_insertion_point(field_mutable:ps.Meta.Node_.hostname)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Meta_Node_::release_hostname() {
  // @@protoc_insertion_point(field_release:ps.Meta.Node_.hostname)
  clear_has_hostname();
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Meta_Node_::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    set_has_hostname();
  } else {
    clear_has_hostname();
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:ps.Meta.Node_.hostname)
}

// required int32 port = 4;
bool Meta_Node_::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Meta_Node_::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
void Meta_Node_::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
void Meta_Node_::clear_port() {
  port_ = 0;
  clear_has_port();
}
::google::protobuf::int32 Meta_Node_::port() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.port)
  return port_;
}
void Meta_Node_::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.port)
}

// optional bool is_recovery = 5;
bool Meta_Node_::has_is_recovery() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Meta_Node_::set_has_is_recovery() {
  _has_bits_[0] |= 0x00000010u;
}
void Meta_Node_::clear_has_is_recovery() {
  _has_bits_[0] &= ~0x00000010u;
}
void Meta_Node_::clear_is_recovery() {
  is_recovery_ = false;
  clear_has_is_recovery();
}
bool Meta_Node_::is_recovery() const {
  // @@protoc_insertion_point(field_get:ps.Meta.Node_.is_recovery)
  return is_recovery_;
}
void Meta_Node_::set_is_recovery(bool value) {
  set_has_is_recovery();
  is_recovery_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.Node_.is_recovery)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Meta::kCmdFieldNumber;
const int Meta::kSenderFieldNumber;
const int Meta::kReceiverFieldNumber;
const int Meta::kTimestampFieldNumber;
const int Meta::kRequestFieldNumber;
const int Meta::kPushFieldNumber;
const int Meta::kNodeFieldNumber;
const int Meta::kDataTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Meta::Meta()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ps.Meta)
}
Meta::Meta(const Meta& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      node_(from.node_),
      data_type_(from.data_type_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&cmd_, &from.cmd_,
    reinterpret_cast<char*>(&push_) -
    reinterpret_cast<char*>(&cmd_) + sizeof(push_));
  // @@protoc_insertion_point(copy_constructor:ps.Meta)
}

void Meta::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&cmd_, 0, reinterpret_cast<char*>(&push_) -
    reinterpret_cast<char*>(&cmd_) + sizeof(push_));
}

Meta::~Meta() {
  // @@protoc_insertion_point(destructor:ps.Meta)
  SharedDtor();
}

void Meta::SharedDtor() {
}

void Meta::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Meta::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Meta& Meta::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Meta* Meta::New(::google::protobuf::Arena* arena) const {
  Meta* n = new Meta;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Meta::Clear() {
// @@protoc_insertion_point(message_clear_start:ps.Meta)
  node_.Clear();
  data_type_.Clear();
  if (_has_bits_[0 / 32] & 63u) {
    ::memset(&cmd_, 0, reinterpret_cast<char*>(&push_) -
      reinterpret_cast<char*>(&cmd_) + sizeof(push_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Meta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ps.Meta)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 cmd = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_cmd();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cmd_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 sender = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_sender();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 receiver = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_receiver();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &receiver_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 timestamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          set_has_timestamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool request = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {
          set_has_request();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &request_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool push = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {
          set_has_push();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &push_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ps.Meta.Node_ node = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 data_type = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 64u, input, this->mutable_data_type())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(66u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_data_type())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ps.Meta)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ps.Meta)
  return false;
#undef DO_
}

void Meta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ps.Meta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 cmd = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cmd(), output);
  }

  // required int32 sender = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->sender(), output);
  }

  // required int32 receiver = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->receiver(), output);
  }

  // required int32 timestamp = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->timestamp(), output);
  }

  // required bool request = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->request(), output);
  }

  // required bool push = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->push(), output);
  }

  // repeated .ps.Meta.Node_ node = 7;
  for (unsigned int i = 0, n = this->node_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->node(i), output);
  }

  // repeated int32 data_type = 8;
  for (int i = 0, n = this->data_type_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      8, this->data_type(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ps.Meta)
}

::google::protobuf::uint8* Meta::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ps.Meta)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 cmd = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cmd(), target);
  }

  // required int32 sender = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->sender(), target);
  }

  // required int32 receiver = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->receiver(), target);
  }

  // required int32 timestamp = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->timestamp(), target);
  }

  // required bool request = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->request(), target);
  }

  // required bool push = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->push(), target);
  }

  // repeated .ps.Meta.Node_ node = 7;
  for (unsigned int i = 0, n = this->node_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, this->node(i), deterministic, target);
  }

  // repeated int32 data_type = 8;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(8, this->data_type_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ps.Meta)
  return target;
}

size_t Meta::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:ps.Meta)
  size_t total_size = 0;

  if (has_cmd()) {
    // required int32 cmd = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cmd());
  }

  if (has_sender()) {
    // required int32 sender = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sender());
  }

  if (has_receiver()) {
    // required int32 receiver = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->receiver());
  }

  if (has_timestamp()) {
    // required int32 timestamp = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->timestamp());
  }

  if (has_request()) {
    // required bool request = 5;
    total_size += 1 + 1;
  }

  if (has_push()) {
    // required bool push = 6;
    total_size += 1 + 1;
  }

  return total_size;
}
size_t Meta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ps.Meta)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000003f) ^ 0x0000003f) == 0) {  // All required fields are present.
    // required int32 cmd = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cmd());

    // required int32 sender = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sender());

    // required int32 receiver = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->receiver());

    // required int32 timestamp = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->timestamp());

    // required bool request = 5;
    total_size += 1 + 1;

    // required bool push = 6;
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .ps.Meta.Node_ node = 7;
  {
    unsigned int count = this->node_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->node(i));
    }
  }

  // repeated int32 data_type = 8;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->data_type_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->data_type_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Meta::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ps.Meta)
  GOOGLE_DCHECK_NE(&from, this);
  const Meta* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Meta>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ps.Meta)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ps.Meta)
    MergeFrom(*source);
  }
}

void Meta::MergeFrom(const Meta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ps.Meta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  node_.MergeFrom(from.node_);
  data_type_.MergeFrom(from.data_type_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      cmd_ = from.cmd_;
    }
    if (cached_has_bits & 0x00000002u) {
      sender_ = from.sender_;
    }
    if (cached_has_bits & 0x00000004u) {
      receiver_ = from.receiver_;
    }
    if (cached_has_bits & 0x00000008u) {
      timestamp_ = from.timestamp_;
    }
    if (cached_has_bits & 0x00000010u) {
      request_ = from.request_;
    }
    if (cached_has_bits & 0x00000020u) {
      push_ = from.push_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Meta::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ps.Meta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Meta::CopyFrom(const Meta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ps.Meta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Meta::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->node())) return false;
  return true;
}

void Meta::Swap(Meta* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Meta::InternalSwap(Meta* other) {
  node_.InternalSwap(&other->node_);
  data_type_.InternalSwap(&other->data_type_);
  std::swap(cmd_, other->cmd_);
  std::swap(sender_, other->sender_);
  std::swap(receiver_, other->receiver_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(request_, other->request_);
  std::swap(push_, other->push_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Meta::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Meta

// required int32 cmd = 1;
bool Meta::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Meta::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
void Meta::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
void Meta::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
::google::protobuf::int32 Meta::cmd() const {
  // @@protoc_insertion_point(field_get:ps.Meta.cmd)
  return cmd_;
}
void Meta::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.cmd)
}

// required int32 sender = 2;
bool Meta::has_sender() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Meta::set_has_sender() {
  _has_bits_[0] |= 0x00000002u;
}
void Meta::clear_has_sender() {
  _has_bits_[0] &= ~0x00000002u;
}
void Meta::clear_sender() {
  sender_ = 0;
  clear_has_sender();
}
::google::protobuf::int32 Meta::sender() const {
  // @@protoc_insertion_point(field_get:ps.Meta.sender)
  return sender_;
}
void Meta::set_sender(::google::protobuf::int32 value) {
  set_has_sender();
  sender_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.sender)
}

// required int32 receiver = 3;
bool Meta::has_receiver() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Meta::set_has_receiver() {
  _has_bits_[0] |= 0x00000004u;
}
void Meta::clear_has_receiver() {
  _has_bits_[0] &= ~0x00000004u;
}
void Meta::clear_receiver() {
  receiver_ = 0;
  clear_has_receiver();
}
::google::protobuf::int32 Meta::receiver() const {
  // @@protoc_insertion_point(field_get:ps.Meta.receiver)
  return receiver_;
}
void Meta::set_receiver(::google::protobuf::int32 value) {
  set_has_receiver();
  receiver_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.receiver)
}

// required int32 timestamp = 4;
bool Meta::has_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Meta::set_has_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
void Meta::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
void Meta::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
::google::protobuf::int32 Meta::timestamp() const {
  // @@protoc_insertion_point(field_get:ps.Meta.timestamp)
  return timestamp_;
}
void Meta::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.timestamp)
}

// required bool request = 5;
bool Meta::has_request() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Meta::set_has_request() {
  _has_bits_[0] |= 0x00000010u;
}
void Meta::clear_has_request() {
  _has_bits_[0] &= ~0x00000010u;
}
void Meta::clear_request() {
  request_ = false;
  clear_has_request();
}
bool Meta::request() const {
  // @@protoc_insertion_point(field_get:ps.Meta.request)
  return request_;
}
void Meta::set_request(bool value) {
  set_has_request();
  request_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.request)
}

// required bool push = 6;
bool Meta::has_push() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Meta::set_has_push() {
  _has_bits_[0] |= 0x00000020u;
}
void Meta::clear_has_push() {
  _has_bits_[0] &= ~0x00000020u;
}
void Meta::clear_push() {
  push_ = false;
  clear_has_push();
}
bool Meta::push() const {
  // @@protoc_insertion_point(field_get:ps.Meta.push)
  return push_;
}
void Meta::set_push(bool value) {
  set_has_push();
  push_ = value;
  // @@protoc_insertion_point(field_set:ps.Meta.push)
}

// repeated .ps.Meta.Node_ node = 7;
int Meta::node_size() const {
  return node_.size();
}
void Meta::clear_node() {
  node_.Clear();
}
const ::ps::Meta_Node_& Meta::node(int index) const {
  // @@protoc_insertion_point(field_get:ps.Meta.node)
  return node_.Get(index);
}
::ps::Meta_Node_* Meta::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:ps.Meta.node)
  return node_.Mutable(index);
}
::ps::Meta_Node_* Meta::add_node() {
  // @@protoc_insertion_point(field_add:ps.Meta.node)
  return node_.Add();
}
::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >*
Meta::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:ps.Meta.node)
  return &node_;
}
const ::google::protobuf::RepeatedPtrField< ::ps::Meta_Node_ >&
Meta::node() const {
  // @@protoc_insertion_point(field_list:ps.Meta.node)
  return node_;
}

// repeated int32 data_type = 8;
int Meta::data_type_size() const {
  return data_type_.size();
}
void Meta::clear_data_type() {
  data_type_.Clear();
}
::google::protobuf::int32 Meta::data_type(int index) const {
  // @@protoc_insertion_point(field_get:ps.Meta.data_type)
  return data_type_.Get(index);
}
void Meta::set_data_type(int index, ::google::protobuf::int32 value) {
  data_type_.Set(index, value);
  // @@protoc_insertion_point(field_set:ps.Meta.data_type)
}
void Meta::add_data_type(::google::protobuf::int32 value) {
  data_type_.Add(value);
  // @@protoc_insertion_point(field_add:ps.Meta.data_type)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Meta::data_type() const {
  // @@protoc_insertion_point(field_list:ps.Meta.data_type)
  return data_type_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Meta::mutable_data_type() {
  // @@protoc_insertion_point(field_mutable_list:ps.Meta.data_type)
  return &data_type_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ps

// @@protoc_insertion_point(global_scope)
